version = "3.8.1"
runner.dialect = scala3
maxColumn = 100
align.preset = more
align.tokens."+" = [
  { code = "=>", owner = "Case" }
]
continuationIndent.defnSite = 2
continuationIndent.ctorSite = 2
docstrings.style = SpaceAsterisk
trailingCommas = always
rewrite.rules = [SortImports, RedundantBraces, PreferCurlyFors]
